name: 'Terraform CI: Validate and Plan'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Infrastructure Validation'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # --- NEW STEP ---
      # Generate a temporary SSH key pair within the runner for this job.
      # The private key will be discarded when the job finishes.
      - name: Generate SSH key
        run: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # --- MODIFIED STEP ---
      # Pass the content of the generated public key to the Terraform plan command.
      - name: Terraform Plan
        run: terraform plan -input=false -var="public_key_content=$(cat ~/.ssh/id_rsa.pub)"
